### ISSUE TITLE
Cannot see Activities for workers who are inactive

### ISSUE THREAD

**Issue by chaim1221** [SavageLearning/Machete#549] opened 2019-08-23 19:13 UTC
Reproduce:

1. Make a worker.
2. Worker inactive.
3. Make an activity.
4. Sign worker into activity.
5. Go to worker profile.

Cannot see activities.

**Comment by esteban-gs** [comment] 2019-11-30 07:17
I was not able to reproduce. Worker activities show sign in.

**Comment by esteban-gs** [comment] 2019-12-29 20:59
Closing, cannot reproduce on version 1.14.186

**Closed by esteban-gs** 2019-12-29 20:59 UTC
