### ISSUE TITLE
Fix Datetime in WorkOrder summary.

### ISSUE THREAD

**Issue by esteban-gs** [SavageLearning/Machete#507] opened 2019-07-13 03:04 UTC
Workorder summary datetime column doesn't match weekday column:

![image](https://user-images.githubusercontent.com/26440947/61166320-3a583680-a4e0-11e9-9baf-e4449a454625.png)

**Comment by esteban-gs** [comment] 2019-07-13 03:05
also this screenshot gif might help: https://savagelearning.slack.com/archives/C0DJEU0E9/p1562986473022200

**Comment by chaim1221** [comment] 2019-07-14 01:40
Duplicate of #505

**Closed by chaim1221** 2019-07-14 01:40 UTC
